// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"book/service/user/rpc/user"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdReq         = user.IdReq
	LoginReply    = user.LoginReply
	LoginReq      = user.LoginReq
	RegistryReq   = user.RegistryReq
	RegistryResp  = user.RegistryResp
	UserInfoReply = user.UserInfoReply

	User interface {
		GetUser(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*UserInfoReply, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error)
		Registry(ctx context.Context, in *RegistryReq, opts ...grpc.CallOption) (*RegistryResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*UserInfoReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) Registry(ctx context.Context, in *RegistryReq, opts ...grpc.CallOption) (*RegistryResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Registry(ctx, in, opts...)
}
