// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type IdReq struct {
	Id int64 `json:"id"`
}

type UserInfoReply struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Number string `json:"number"`
	Gender string `json:"gender"`
}
