// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegistryReq struct {
	Username string `json:"username"`
	Number   string `json:"number"`
	Gender   string `json:"gender"`
	Password string `json:"password"`
}

type RegistryResp struct {
	Username string `json:"username"`
	Number   string `json:"number"`
	Gender   string `json:"gender"`
	Detail   string `json:"detail"`
}

type IdReq struct {
	Id int64 `form:"id"`
}

type UserInfoReply struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Number   string `json:"number"`
	Gender   string `json:"gender"`
}
